version: "3"
services:
  native:
    image: annabogacheva/servimag
    hostname: NATIVE78
    expose:
      - 9090/udp
    environment:
      - HOST=NATIVE
      - PORT=9090

  xml:
    image: annabogacheva/servimag
    hostname: XML78
    expose:
      - 9090/udp
    environment:
      - HOST=XML
      - PORT=9090

  json:
    image: annabogacheva/servimag
    hostname: JSON78
    expose:
      - 9090/udp
    environment:
      - HOST=JSON
      - PORT=9090

  apache:
    image: annabogacheva/servimag
    hostname: APACHE78
    expose:
      - 9090/udp
    environment:
      - HOST=APACHE
      - PORT=9090

  yaml:
    image: annabogacheva/servimag
    hostname: YAML78
    expose:
      - 9090/udp
    environment:
      - HOST=YAML
      - PORT=9090

  msgpack:
    image: annabogacheva/servimag
    hostname: MSGPACK78
    expose:
      - 9090/udp
    environment:
      - HOST=MSGPACK
      - PORT=9090

  client:
    image: annabogacheva/clientimg
    hostname: client
    expose:
      - 2000/udp
    ports:
      - "2000:2000/udp"
    environment:
      - PORT=9090
    depends_on:
      - native
      - xml
      - msgpack
      - json
      - apache
      - yaml